# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: CM(CK2) script automation readme update

on:
  pull_request:
    branches: [ "master", "dev" ]
    paths:
      - '.github/workflows/update-script-readme.yml'
      - '!cm-mlops/script/**.md'
      - 'cm-mlops/script/**'

jobs:
  doreadme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: (CI) Dependencies update check
      run: |
        files=`git diff-tree --no-commit-id --name-only -r ${{ github.sha }}`
        echo $files
