# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: CM(CK2) script automation readme update

on:
  pull_request:
    branches: [ "master", "dev" ]
    paths:
      - '.github/workflows/update-script-readme.yml'
      - '!cm-mlops/script/**.md'
      - 'cm-mlops/script/**'

jobs:
  doreadme:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: get changed files
      id: getfile
      run: |
        echo "::set-output name=files::$(git diff-tree --no-commit-id --name-status -r ${{ github.sha }} | xargs)"
    - name: echo output
      run: |
        echo ${{ steps.getfile.outputs.files }}
