# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: CM(CK2) script automation readme update

on:
  pull_request:
    branches: [ "master", "dev" ]
    paths:
      - '.github/workflows/update-script-readme.yml'
      - '!cm-mlops/script/**.md'
      - 'cm-mlops/script/**'

jobs:
  doreadme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: (CI) Dependencies update check
      run: |
        current_commit=`git log -n 1 --pretty=format:%H`
        echo $current_commit
        last_deps_mod_commit=`git log -n 1 --pretty=format:%H -- composer.json`
        echo $last_deps_mod_commit
        if [ $current_commit == $last_deps_mod_commit ]; then echo USE_LOCK=0 > ci.conf; else echo USE_LOCK=1 > ci.conf; fi
