# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: CM(CK2) script automation readme update

on:
  pull_request:
    branches: [ "master", "dev" ]
    paths:
      - '.github/workflows/update-script-readmes.yml'
      - '!cm-mlops/script/**.md'
      - 'cm-mlops/script/**'

jobs:
  doreadme:
    runs-on: ubuntu-latest
    steps:
    - id: files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'csv'
    - run: |
        mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
        for added_modified_file in "${added_modified_files[@]}"; do
          echo "Do something with this ${added_modified_file}."
        done
