# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: CM(CK2) script automation readme update

on:
  push:
    branches: [ "master", "dev" ]
    paths:
      - 'cm-mlops/script/**_cm.json'

jobs:
  doreadme:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get changed files
      id: getfile
      run: |
        echo "files=$(git diff --name-only ${{ github.event.before }} | xargs)" >> $GITHUB_OUTPUT
    - name: echo output
      run: |
        echo ${{ steps.getfile.outputs.files }}
        for file in ${{ steps.getfile.outputs.files }}; do
          echo $file
        done
        python3 -m pip install cmind
        cm pull repo --url=https://github.com/${{ github.repository }} 
        # --checkout=${{ github.ref }}
        python3 tests/script/process_readme.py ${{ steps.getfile.outputs.files }}
        REPO=${{ github.repository }}
        echo $REPO
        CM_REPO=${REPO/\//@}
        echo $CM_REPO
        FOL=`cm find repo ${CM_REPO}`
        echo $FOL
        FOLDER=`cm find repo ${CM_REPO} | cut -d' ' -f3`
        FOLDER=`cm find repo mlcommons@ck | cut -d' ' -f3`
        echo $FOLDER
        cd $FOLDER
        echo "Po"
        git config --global user.name '{{ github.repository_owner }}'
        git config --global user.email '{{ github.repository_owner }}@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}
        git add *.md
        git commit -a -m "Updated docs"
        git push
