# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: CM(CK2) script automation readme update

on:
  pull_request:
    types:
    - closed
    branches: [ "master", "dev" ]
    paths:
      - 'cm-mlops/script/**_cm.json'

jobs:
  doreadme:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get changed files
      id: getfile
      run: |
        git checkout ${{ github.base_ref }}
        echo "files=$(git diff --name-only ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
    - name: echo output
      run: |
        echo ${{ steps.getfile.outputs.files }}
        for file in ${{ steps.getfile.outputs.files }}; do
          echo $file
        done
        git checkout ${{ github.event.pull_request.head.ref }}
        python3 -m pip install cmind
        cm pull repo --url=${{ github.event.pull_request.head.repo.html_url }} --checkout=${{ github.event.pull_request.head.ref }}
        python3 tests/script/process_readme.py ${{ steps.getfile.outputs.files }}
        REPO=${{ github.event.pull_request.head.repo }}
        echo $REPO
        CM_REPO=${REPO/\//@}
        echo $CM_REPO
        cd `cm find repo ${CM_REPO}`
        git config --global user.name 'Admin'
        git config --global user.email 'admin@users.noreply.github.com'
        #git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git add *.md
        git commit -a -m "Updated docs"
        git push
